# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170518_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hiking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=60)),
                ('distance', models.CharField(max_length=60)),
                ('numberOfDays', models.IntegerField()),
                ('typeOfTerrain', models.CharField(choices=[('Hilly', 'Hilly'), ('Flat', 'Flat'), ('Mixed', 'Mixed')], max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=256)),
                ('grade', models.CharField(max_length=100)),
                ('sendStatus', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('belayer', models.CharField(max_length=100)),
                ('betaSpew', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='blogPosts',
            new_name='BlogPost',
        ),
        migrations.RenameModel(
            old_name='tripCost',
            new_name='Cost',
        ),
        migrations.RenameModel(
            old_name='milesTraveled',
            new_name='DistanceDriven',
        ),
        migrations.RenameModel(
            old_name='mapMarkers',
            new_name='MapMarker',
        ),
    ]
