# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoEngine', '0002_photo_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='is_cover_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(blank=True, to='photoEngine.Tag'),
        ),
    ]
